fjosw/pyerrors

- pyerrors/input/json.py
- tests/io_test.py
Adjusted handling of tags: All are written, if any is None; Removed unnused parameter fname from create_json_string; Created a fail-save version for the replacement of quotation marks in workaround for delta lists.
A more elegant solution for the nice output, currently done via the deltalist class, should be possible by a modification of the JSON encoder.
Closes #13
> Resolves issue 

- pyerrors/correlators.py
- pyerrors/input/json.py
Okay, i repulled and redid the changes in the correlators file only. 
Are you sure, that i should not update my example data?
> Changes in the correlator init, GEVP and docstrings & tag format includes dict and prange

- pyerrors/correlators.py
- tests/correlators_test.py
The parameter which distinguishes between the variant is now a string instead of a bool which may break current analyses.
> feat!: Implemented improved first and second derivatives for the corresponding methods of the Corr class.

- pyerrors/input/json.py
- tests/io_test.py
As discussed in #19 this pull request introduces the I/O for dictionaries that contain JSON-valid structures and Obs-structures (Obs, Corr, numpy.ndarray, list). The structure of the file format has not been touched (neither have the existing routines, apart from the correction of a misspelling.)
> Introduced JSON I/O for dictionaries

- pyerrors/input/json.py
- tests/json_io_test.py
> fix: Bug in export of derivative of correlator containing covobs fixed, test added.

- pyerrors/correlators.py
> auto_gamma parameter introduced to Corr.show

- pyerrors/correlators.py
- tests/correlators_test.py
- tests/obs_test.py
spaghetti_plot method for monitoring exceptional configurations added to Corr class, test added.
> feat: spaghetti_plot

- pyerrors/input/bdio.py
The handling of the configuration numbers had not been implemented for ```read_mesons``` and ```read_dSdm```. We now return the correct idl based on the information in the bdio files. It is also possible to choose a sub-set of the data using the keywords ```start```, ```stop``` and ```step```.
> Fix: read_mesons and read_dSdm now return Obs with the correct idl based on the information in the bdio file.

- pyerrors/input/bdio.py
Solves #92. Also contains speedup of the Obs creation and a small bug fix concerning the output.
> Removed sorting of kappas and speed improvement in read_mesons

- pyerrors/correlators.py
- tests/correlators_test.py
- tests/fits_test.py
The log-derivatives are defined as 
$\partial_t C(t) = C(t) \cdot \partial_t \log[C(t)] $
and
$\partial_t^2 C(t) = C(t) [\partial_t^2 \log[C(t)] + ( \partial_t \log[C(t)])^2] $
and they are exact for single-exponential functions, i.e., they do not induce any discretization error. Of course, the user could implement these themselves, but I find this way more convenient.
I have also added the log-effective mass based on a symmetric derivative.
> feat: added log-derivatives and symmetric effective mass

- pyerrors/input/hadrons.py
- pyerrors/input/openQCD.py
Draft: method added to read the data of xsf measurement code
> first version of skript to read xsf data

- pyerrors/roots.py
- tests/roots_test.py
Added the possibility to calculate roots of functions of multiple `Obs`.
> Root of multi parameter functions

- pyerrors/correlators.py
> Color and zorder for prange indicator in Corr.show added.

- pyerrors/input/__init__.py
> fix: dobs import added to input/__init__.py

- pyerrors/correlators.py
- pyerrors/obs.py
- tests/correlators_test.py
- tests/obs_test.py
I added a `__eq__` method for the `Corr` class for simpler checks like `corr == 0`.
> __eq__ method for Corr class

- pyerrors/input/hadrons.py
Closes #217 
Can you check if this fixes your issue (and does not cause problems in other places) @jkuhl-uni ?
> [fix] fixed how the filestem is extracted in hadrons/read_hdf5.

- pyerrors/input/sfcf.py
Hi,
as I had a weird error message a few days ago, I created a case where this is covered specifically to improve the understandability of the errors thrown.
Cheers,
Justus
> Catch error if no replica are found in the geiven directory

- pyerrors/input/sfcf.py
Hi,
I just saw a small problem, where debug data is printed still. I just erased the line. Sorry for the inconvenience
> erase print rep data

- pyerrors/__init__.py
- pyerrors/correlators.py
- pyerrors/dirac.py
- pyerrors/input/__init__.py
- pyerrors/input/dobs.py
- pyerrors/input/hadrons.py
- pyerrors/input/openQCD.py
- pyerrors/obs.py
- tests/correlators_test.py
- tests/dirac_test.py
- tests/obs_test.py
This PR applies a few PEP 8 corrections and makes the types of Exception more precise.
> [Fix] Ruff rules and more precise Excpetion types

- pyerrors/fits.py
This minor change corrects an error message that otherwise is not very helpful.
> [fix] Corrected an error message

- pyerrors/input/json.py
addresses the failed checks in #261
> [Fix] removed unnecessary lines that raised the flake8 error code F824

- setup.py
> setup.py: Drop deprecated license classifiers
