pyerrors/obs.py

Removing a bug that was present for vanishing obs and irregular chains.

Bug-Fix: Do not apply filter if all deltas vanish, i.e., if Obs is zero

---

pyerrors/input/json.py
tests/io_test.py

This feature contains a first implementation for the input from and output to a new .json.gz format. 
A workaround had to be applied to have indentation (and not to have all information in a single line) in combination with the [cnfg, deltas] entries printed in a single line.
This is up for discussion. The Zeuthen dobs format might be as efficient (an implementation of the corresponding I/O will follow). However, anyone with a json-implementation should be able to parse the new file format easily.

First implemenation of a json I/O

---

pyerrors/input/json.py
tests/io_test.py

Included covobs in the json file format using the additional entry "cdata" that is written right after "data". It is also possible to export/import Obs that are pure covobs, i.e., that do not have any deltas.

covobs in json I/O

---

pyerrors/fits.py
tests/fits_test.py

... also allows to pass method='Levenberg-Marquardt' explicitly. Closes #51.

Fixes least_squares with migrad, tests extended

---

pyerrors/input/openQCD.py

We now read the configuration numbers in the case of RWFs to ensure the correctness of idl.
In the case of t0, this is more difficult, because we only know the number of the HMC trajectory or SMD cycle. It is now assumed, that the first measurement belongs to the first config and that a possible offset is due to thermalization. A warning is thrown, if an offset is present. There is a new optional keyword to change this behavior and to assume that no thermalization is present in the MC run.
We do not correctly handle cases where the distance between two measurements is not equal to the distance between two configurations. It is hard to catch all cases and I would not know how to handle the idl consistently, if the distance between to measurements is smaller than the config distance. For …

Ensure correctness of idl in RWFs and t0

---

pyerrors/obs.py
tests/obs_test.py

There was a stupid bug in _reduce_deltas, that involved a NxN double loop. The change leads to a speedup of N/2. Especially relevant for irregular MC chains or reweighting.,
Added tests to ensure correctness of the function.

Bugfix in _reduce_deltas. Results were correct, but performance was bad

---

pyerrors/input/json.py

With this little fix I am covering a very special case which should never happen with files written by pyerrors. This fix explicitly makes sure that the replica separator `|` is enforced in case another program wrote a json file with a different separator. This fix would imply that the separator `|` is not part of the format specification and would allow other implementations to use other separators.

fix: erroneous replica separator in json format caught and corrected

---

examples/02_correlators.ipynb
examples/04_fit_example.ipynb
examples/06_gevp.ipynb
pyerrors/correlators.py
tests/correlators_test.py

Calls to the gamma_method removed in Corr.__init__ and other methods of the Corr class.
Tests adjusted by adding additional calls to the `gamma_method`.
Closes #67

Implicit calls to the gamma_method removed from methods of the Corr class

---

pyerrors/input/sfcf.py

Bug fixed that some files aren't closed in read method. Forgot to close the files that are used to look where the fitting correlator can be found in the files.

bug fix: read methods are in fact closing files now

---

examples/json_schema.json

This JSON schema may be used to check whether a file is valid with respect to the JSON file format that we have defined. This validation is not able to find any type of bug, e.g., if the layout and the number of entries per config inside a structure match. However, anyone can use it to check whether his or her own implementation of the file format is written in the correct way.
As side effect, this is a self-contained documentation of the file format. I intend to write a more concise definition for the pyerrors documentation. If we like to have this schema as self-contained explanation, some more information on the different types of entries will have to be given in the "description" tags. (Probably we can use the same text for both tasks).
Feel free to comment on this and to suggest …

Added JSON schema for validation and documentation purposes

---

pyerrors/correlators.py

`GEVP` method now uses `scipy.eigh()` and applies matrix_symmetric().
`Eigenvalue` takes the same arguments as `GEVP` and projects automatically.

Changes to Eigenvalue

---

pyerrors/obs.py
tests/obs_test.py

This fixes a bug when combining Obs that are defined on irregular MC chains:
The following snipped 
```python
import pyerrors as pe
a = pe.pseudo_Obs(1, .1, 'a', samples=10)
a.idl['a'] = range(4, 15)
b = pe.pseudo_Obs(1, .1, 'a', samples=151)
b.idl['a'] = range(4, 608, 4)
ol = [a, b]
o = (ol[0] - ol[1]) / (ol[1])
```
throws an exception
```
...pyerrors/obs.py in _expand_deltas_for_merge(deltas, idx, shape, new_idx)
996         if idx == new_idx:
997             return deltas
--> 998     ret = np.zeros(new_idx[-1] - new_idx[0] + 1)
999     for i in range(shape):
1000         ret[idx[i] - new_idx[0]] = deltas[i]
ValueError: negative dimensions are not allowed
```
The reason is that _expand_deltas_for_merge expects new_idx to be sorted. This had not been ensured before.

_merge_idx now returns sorted lists

---

.github/workflows/flake8.yml
CONTRIBUTING.md
pyerrors/fits.py
pyerrors/obs.py
tests/covobs_test.py
tests/fits_test.py
tests/obs_test.py

I removed the `fits.covariance_matrix` function and adjusted `covariance` to operate on a list of observables and return a matrix.
I also reworked the way the covariance is estimated and I believe that the new estimator ensures positive semi-definiteness of the covariance matrix up to machine precision. The `covariance` function now also allows for a direct visualization of the corresponding (normalized) correlation matrix. I also added additional tests for the covariance.

Reworked covariance

---

pyerrors/obs.py

I think the line `np.sum(np.ones_like(idl_d[r_name]))` is equivalent to `len(idl_d[r_name])` but the second option is simpler and faster. Can you confirm that @s-kuberski ?

Simplification and speed up of the computation of e_N in _covariance_element

---

pyerrors/obs.py

When working with spaced and irregular data it can occur that `gamma` and `gamma_div` are both numerically zero for some windowsizes. In the ratio of 0 / 0 odd rounding errors can occur. With this fix I propose to set all elements of `gamma_div` that are smaller than 1 to 1 which should not affect the standard error estimation.

Prevent division by zero by setting values of gamma_div which are smaller than 1 to 1

---

pyerrors/fits.py
tests/fits_test.py

In some tests I ran today I noticed that the matrix `A.T @ A` which has to be inverted for our estimation of the expected chisquare can be numerically very close to singular in some cases. One (at least temporary) solution would be to replace the inverse by the Moore-Penrose pseudo inverse which would filter out the directions corresponding to the almost vanishing singular values. In my test the estimator for the expected chisquare became negative when using the standard inverse but was quite close to the "true" correlated chisquare value when using the pseudo inverse. As I am not using this feature on a regular basis I wanted to ask for other opinions.

Replaced inverse by the pseudo inverse in the calculation of chi_exp

---

pyerrors/obs.py

I propose to increase the standard values for the precision which is required for two observables to be considered equal. The formula which is used within numpy is `absolute(a - b) <= (atol + rtol * absolute(b))` (https://numpy.org/doc/stable/reference/generated/numpy.isclose.html).

Precision of is_zero

---

pyerrors/input/json.py
setup.py

This change from json to rapidjson helps to achieve an order of magnitude of speedup when writing large JSON files to disk. At the same time, the memory footprint is smaller. The option ```write_mode=json.WM_SINGLE_LINE_ARRAY``` allows to get rid of the ugly workaround for having a human readable format, if indent!=0. 
This would add the dependence on ```python-rapidjson``` (I have not added this to the ```setup.py```, because I like to discuss it first). We could insert something like 
```python
try:
import rapidjson as json
except ImportError:
import json
```
to allow the user to do the export using the ```json``` module and to improve performance by installing ```rapidjson```. This would need some small adjustments in ```create_json_string``` to handle both cases appropriately.

Use rapidjson instead of json for I/O

---

examples/06_gevp.ipynb
pyerrors/correlators.py
tests/correlators_test.py

I propose to make two additional **breaking** changes to `Corr.GEVP`. With my patch
- the `GEVP` method now returns all vectors instead of just the ones for a specified state. Since we compute all vectors anyways this saves unnecessary overhead and also eliminates the argument `state`. If only one state is of interest the corresponding vectors can be obtained via indexing
```
C.GEVP(t0=2)[0]  # Ground state vectors
C.GEVP(t0=2)[:3]  # Vectors for the lowest three states
```
- the argument `sorted_list` was renamed to `sort` which feels like a more meaningful name.
I also simplified the `_solve_GEVP` helper function, the functionality should be unchanged. I added a unit test which verifies this.
Opinions?
Depends on PR #99

GEVP rehaul 2

---

pyerrors/input/json.py
tests/json_io_test.py

This fixes a bug in the JSON I/O: 
The definition of the JSON file format states that the deltas that are saved in the file are the deviations on each ensemble relative to **the mean value**. However, we did export the deviation relative to the **replica mean**. This led to a loss of information namely the mean values on the single replica, which were set to the global mean value after import.
The bug fix now ensures that the correct replica means are restored. Within the file, the deltas within one entry `'deltas'` do not sum to zero anymore, but to `r_value - value`. The sum of all deltas within one ensemble still sums up to zero. This could be used as a cross-check. I am thinking about how to implement this, together with a speedup of the import.
Old files that were written with the …

bugfix: Deltas in JSON file are now relative to o.value and not o.r_values[r_name]

---

pyerrors/input/json.py
tests/json_io_test.py

I think I found another bug which only appears in the reconstruction of observables defined on multiple replica for which the average of the `r_values` is **not** equal to the `value`. In these cases the correct value was not reconstructed but instead the average of the `r_values` was assigned.

Bug in json format value assignment

---

pyerrors/fits.py
tests/fits_test.py

When attempting a correlated fit I propose to always do an uncorrelated fit first in order to guess appropriate starting values.

Prefit correlated fits

---

pyerrors/input/__init__.py
pyerrors/input/pandas.py
setup.py
tests/pandas_test.py

I added export and import functionality for pandas `DataFrames` with `Obs` type columns to efficiently handle large data sets. On my local machine writing and reading O(8000) `Obs` with 9 columns of metadata (strings, ints and floats) takes less than a second each.
The serialization of the `Obs` objects is based on our standardized json format. The DataFrame is stored as a (gzipped) csv file on disk. Storage as a (gzipped) json file would work equally well but I figured that the additional metadata the json file would contain is irrelevant in this context.

Pandas DataFrame support

---

pyerrors/obs.py
tests/obs_test.py

This is my first attempt at a reproducible hash function for `Obs` objects. I construct a tuple out of the value, the deltas, the errsq of the covobs and the names and hash that. All numerical values are cast to single precision via numpy which hopefully takes care of any rounding errors that can occur.

hash method for Obs objects

---

pyerrors/correlators.py
tests/correlators_test.py

I implemented a new method `is_matrix_symmetric` which uses the new hash function to efficiently check whether a correlator matrix is symmetric. This check is now performed within `matrix_symmetric` and speeds up the method in case the matrix is already symmetric. This in turn accelerates the GEVP method which always calls `matrix_symmetric`.

is_matrix_symmetric

---

pyerrors/fits.py
tests/fits_test.py

I implemented the option to perform the error propagation for least squares fits with numerical differentiation instead of automatic differentiation. Using this option is ~~considerably~~ slower but can deal with fit functions which contain special functions or which are not analytically known.

Least square fit with numerical differentiation

---

pyerrors/obs.py
tests/obs_test.py

This addresses the issue and discussion in #123. 
A few comments:
- `gapsize` is determined from the first replica, assuming that it is the same for all of them. A check could be done upon initialization of the (derived) obs. I had the feeling that it should not be done when the gamma method is called.
- The fix for the critical slowing down analysis seems to be rather trivial. I hope that everything is done correclty here. I have not yet implemented a test for this feature, this should probably be done. A general issue is in handling tau_exp. We could use `tau_exp` in units of `configs` instead of the step size in the case of regular, gapped MC chains. This could avoid a lot of confusion.
- We have to decide how to display the integrated autocorrelation times (and windows). The standard …

fix: bug in automatic window for irregular chains fixed

---

pyerrors/obs.py
tests/obs_test.py

This PR fixes the calculation of `dtauint` for gapped irregular chains which appeared in connection with #124. The missing part was to divide `np.abs(np.arange(w_max)` by `gapsize`. I also added a test which checks this.

Fix: gapped irregular dtauint

---

pyerrors/obs.py

I reworked the output of the `details` method based on the discussion in #124.
In addition to that I added greek unicode characters where applicable, changed the output of tau_int with its error to paranthesis notation and adjusted the right alignment of the information about the windowing procedure.
The output for an observable with support on a single ensemble looks like this:
```
Result	 1.38625189e+01 +/- 2.95299110e-01 +/- 8.34709829e-02 (2.130%)
τ_int	 121(51) in units of 1 config         	(S=2.00)
5000 samples in 1 ensemble:
· Ensemble 'B20' : 5000 configurations (from 1 to 5000)
```
and for multiple ensembles like this:
```
Result	 1.30947356e+01 +/- 1.17152209e+00 +/- 3.83826885e-01 (8.947%)
Ensemble errors:
A10 	 1.130136e+00 +/- 3.971589e-01
τ_int	 119(36) in units of 1 config …
```

Improved details output

---

pyerrors/obs.py
tests/obs_test.py

This PR speeds up the computation of covariance by orders of magnitude, when irregular MC chains are involved.
I removed `_collapse_deltas_for_merge` as it did the same job as `_reduce_deltas`. I also improved the implementation of `_reduce_deltas`, mainly by changing two things:
- I now use `groupby` to check if to `idx` are equal. For covariance matrices of correlators, this means that no reduction has to be performed, at all. In principle, this is already checked in `_intersection_idx` within `_covariance_element` such that we could do some rewriting: Export a boolean that tells you if all lists are equal when calling `_intersection_idx` and use this to skip the call for the reduction in `calc_gamma`. However, I have the impression that the comparison using groupby is very efficient …

feat: Speed up covariance for irregular MC chains

---

pyerrors/obs.py
tests/obs_test.py

This PR fixes a bug that appears when calling `Obs.details` on an observable for which the integrated autocorrelation time was determined to be 0.5 with zero error.

Fix details w/ no autocorrelation

---

pyerrors/input/json.py

This change handles cases where entries of the data structure that is to be exported to a JSON file, e.g., via `pe.input.json.dump_dict_to_json` contains a `numpy.int64`. Before, an error has been thrown, because the `dunps` function now gets a plain `int` via the type conversion. If any more such cases exist, they could be included in the new function `_jsonifier'.

feat: JSON export can handle numpy.int64 entries

---

pyerrors/input/openQCD.py

The projection to sectors of the topological charge was not done correctly in the case of several replica because the value of the primary observable had been extracted from the mean and not the replica mean. 
The impact of this bug is expected to be very minor since it only has an impact, if the difference between mean and replica mean leads to a shift from one sector to the other.

fix: corrected small bug in qtop_projection with several replica

---

pyerrors/obs.py
tests/correlators_test.py

This PR removes the filtering of `idls` in `derived_observable`.
Closes #138

fix: remove _filter_zeroes

---

pyerrors/input/json.py
pyerrors/input/openQCD.py
pyerrors/misc.py
pyerrors/obs.py
tests/correlators_test.py
tests/json_io_test.py
tests/linalg_test.py

This PR removes the `Obs` attribute `is_merged` which is no longer needed after the removal of `_filter_zeroes`. On my machine, on python 3.8 this results in a ~1.15x speed up for the multiplication of two `Obs`.

Remove attribute is_merged

---

pyerrors/dirac.py
pyerrors/fits.py
pyerrors/input/bdio.py
pyerrors/input/dobs.py
pyerrors/input/hadrons.py
pyerrors/input/json.py
pyerrors/input/misc.py
pyerrors/input/openQCD.py
pyerrors/input/pandas.py
pyerrors/input/sfcf.py
pyerrors/input/utils.py
pyerrors/misc.py
pyerrors/mpm.py
pyerrors/roots.py

Inspired by the automatically generated docstrings from my last pull request and some questions that I got from someone working with the fit functions, I started adding Return statements in .addition to the usual parameter statements.
So far I have worked on the input methods. Of course, this is only a part of the full job.
I intend to add more of these in the future, if there is interest in having this. In my opinion this could be quite practical for people who are new to the code and who work with IDEs that show doctrings as hints (e.g. VS Code).
In fact I noticed, that there are already statements like these in the docstrings for some methods, however I thought having them in the same standardized format as the parameters could be good.
Of course I'd be more than happy for additional …

better docstrings

---

pyerrors/correlators.py
tests/correlators_test.py

Corr.symmetric can now deal with None entries.

---

pyerrors/misc.py
tests/misc_test.py

I added a wrapper around `plt.errorbar` or `Axes.errorbar` for use with `Obs` objects which should save a bit of time everytime one tries to plot and Obs valued list or array.
Usage:
```python
import matplotlib.pyplot as plt
import pyerrors as pe
...
pe.errorbar(x, y, marker="o")
plt.show()
or
fig = plt.figure()
ax1 = fig.add_subplot(111)
pe.errorbar(x, y, marker="o", axes=ax1)
plt.show()
```

Wrapper for errorbar matplotlib method

---

pyerrors/input/dobs.py
pyerrors/obs.py
tests/json_io_test.py
tests/obs_test.py

Fixes a critical bug that in some cases underestimated the error when different `idl`s for the same ensemble were used.

Fix non overlapping configurations

---

pyerrors/obs.py

I recently looked at simulations where I have access to more than a million samples and noticed that the standard windowing procedure can become very slow because most of the time is spent computing the error of rho which is not needed for the windowing but only when visualizing rho as a function of the window. For this reason I propose to remove the computation of drho for the standard windowing procedure. On my machine in a test setup with 5 million samples and $\tau_\mathrm{int}\approx 150$ the gamma method took 20.4s with the previous version and 820ms after the change.
The only downside that I can see is that the error of rho is not available for every data point when calling the `plot_rho` method. I attached how the output of this method looks like with the changes I propose.

feat: removed computation of drho from standard windowing procedure.

---

pyerrors/correlators.py

This PR adds the `__slots__` class attribute to the `Corr` class which should result in a few percent memory saving per `Corr` instance.

feat: added __slots__ to Corr class.

---

.github/workflows/flake8.yml
CONTRIBUTING.md
pyerrors/obs.py
tests/obs_test.py

This PR fixes `_compute_drho` for `i>w_max // 2` and closes #156. Irrespective of this we should maybe think about how the `gamma_method` should deal with observables that have values like `nan` and `inf`.

_calculate_drho for large time separations

---

pyerrors/correlators.py
pyerrors/fits.py
tests/fits_test.py

I started refactoring the fit code and removed the `_standard_fit` function by merging its functionality with `_combined_fit`. All tests pass so it looks like nothing went wrong in the process but please have a close look @s-kuberski & @PiaLJP .

refactor: _standard_fit method made redundant.

---

pyerrors/fits.py

This is the second step in refactoring the fit module in which I removed redundant formulations of the chisquare function. Please have another close look @s-kuberski & @PiaLJP

Refactor chisquare function in least squares

---

pyerrors/fits.py
tests/fits_test.py
tests/obs_test.py

In this PR I combined `_combined_fit` and `_prior_fit` and eliminated duplicate code.
I also extended the prior fit functionality. Priors can now also be provided via a dictionary with integer keys. For example:
```python
prior_dict = {0: "2.0(7)",
2: "1.12(2)"}
pe.least_squares(x, y, fitf, priors=prior_dict)
```
would only impose priors for parameters 0 and 2 and leave all other parameters unconstrained.
I think this PR closes #38 I added a test that demonstrates that constraining a constant fit parameter with a very precise prior is equivalent to subtracting the prior from the data.
Please have a close look at the changes and do some tests of your own if possible as this is quite a substantial change to the fitting functionality together with the changes in #154 and #158

Improved prior fit

---

pyerrors/input/pandas.py
tests/pandas_test.py

I added the option to serialize lists of `Obs` when writing a pandas DataFrame to an sql database.

Serialize list of Obs in pandas.to_sql

---

pyerrors/correlators.py
tests/fits_test.py

Plots for combined fit. Added function keys to corr.show

NHT changes plots combined fit

---

pyerrors/input/json.py
tests/json_io_test.py

This restores the behavior of the JSON export for `dict` that has been working with the standard `json` package. When using `rapidjson`, the conversion of dict keys that are not strings to strings is not performed automatically anymore. The updated implementation is based on the suggestions in https://python-rapidjson.readthedocs.io/en/latest/dumps.html 
`np.int` and `np.floating`, e.g. in the description of the json file, are now also properly handled.

Restored JSON output of dicts with non-string keys

---

tests/obs_test.py

PR #172 introduced a warning in the tests as `rho` can become larger than one which results in the computation of the square root of a negative number. I adjusted the maximal value for `rho` to 1.

Adjusted maximal value for rho in test_gamma_method_irregular.

---

pyerrors/obs.py
tests/obs_test.py

I finally got the indexing in the `_compute_drho` routine correct. My last fix did not solve all the edge cases that one can find and in one case, I ran into an error because the code tried to add arrays of non-equal size. I am fairly sure that the counting is now correct.

Bug fix for edge case in _compute_drho

---

pyerrors/covobs.py
pyerrors/input/dobs.py
pyerrors/obs.py

With the upcoming release of numpy 1.25 we are hitting a few deprecations. This a fix for
>Only ndim-0 arrays are treated as scalars. NumPy used to treat all
arrays of size 1 (e.g., np.array([3.14])) as scalars. In the
future, this will be limited to arrays of ndim 0 (e.g.,
np.array(3.14)).
Please check that this does not break anything.

Conversion of an array with ndim > 0 to a scalar deprecation fixed

---

pyerrors/input/sfcf.py

I just experimented with changing the ci to fail on warnings which caused the following error:
```bash
pytest -vv -Werror
...
FAILED tests/sfcf_in_test.py::test_find_corr - pytest.PytestUnraisableExceptionWarning: Exception ignored in: <_io.FileIO [closed]>
```
I was able to fix it by using a context manager in `input.sfcf._find_correlator`. Please have a look @jkuhl-uni and make sure that I did not break anything.

fix bug in _find_correlator

---

pyerrors/obs.py
tests/obs_test.py

I added the functionality to bootstrap resample an `Obs` with given random numbers or via random numbers generated from the ensemble name.
If the number of bootstrap samples is larger than the number of Monte Carlo samples the bootstrap samples can then be reimported into an `Obs`.

Bootstrap export/import

---

pyerrors/correlators.py
pyerrors/obs.py
tests/obs_test.py

I worked a bit on the string conversion of complex observables and correlators.
- `CObs` now have a `__format__` method which allows for f-string formatting like this: 
```python
print(f"{my_cobs:+3}")
> (+0.018(465)+0.443(393)j)
```
- I use this to also improve the print output of complex correlators which now produces the following:
```python
Corr T=4 N=1
x0/a	Corr(x0/a)
------------------
0	(+0.02(46)+0.44(39)j)
1	(+0.00(59)+0.43(37)j)
2	(+0.01(58)+0.64(47)j)
3	(-0.03(62)+0.45(51)j)
```
Please have a look @JanNeuendorf
PS: There is still no proper print output for matrix correlators.

CObs format added and complex Corr print improved.

---

pyerrors/fits.py
tests/fits_test.py

This PR addresses an issue in combined fits that @PiaLJP had seen in the past and @matteo-dc ran into this week:
When doing a combined fit and one of the fit functions is just a constant then the shape casting fails and one gets an error. The solution we found in the past is to add `x * 0` to the constant in the fit function to obtain the correct shape.
This PR does not fix the issue as I wasn't able to come up with a good solution, yet. Instead, I added an explicit exception that informs the user and suggests our workaround. For the future, it would of course be desirable to correct the shape casting for this edge case.

Explicit Exception for combined fit edge case

---

pyerrors/correlators.py
tests/correlators_test.py
tests/fits_test.py

I overloaded the matmul class which should now allow for the multiplication of matrix valued `Corr` objects with matrices. I will write a few tests and look into edge cases but this solution seems to work.

Matmul overloaded for correlator class.

---

pyerrors/input/hadrons.py

Fixed the splitting of the meson string. This was a problem when the hdf5 group has multiple underscores.

Split meson on last underscore in read_meson_hdf5

---

pyerrors/correlators.py
tests/correlators_test.py

I generalized the initialization of the `Corr` class. Correlators can now additionally be initialized with
- One-dimensional arrays (equivalent to a list)
- Three-dimensional arrays of shape (T, N, N)
I think I did not touch what happens to lists and two-dimensional arrays. Please have a close look.

Corr array initialization generalized

---

pyerrors/input/hadrons.py

I added a more general hadrons hdf5 reader which can identify entries based on a dictionary of attributes. The function can also extract either the real or imaginary part or a complex correlator. `read_meson_hd5` now calls the new function preserving the old functionality. Compared to `read_meson_hd5` the new function has a cleaner interface with fewer arguments.

General hadrons hdf5 reader added

---

pyerrors/correlators.py
pyerrors/obs.py
tests/correlators_test.py
tests/obs_test.py

I added the missing overloading of the addition of `Obs` and `complex` and the addition and multiplication of `Corr` and `complex` types.

Added support for addition and multiplication of complex numbers to Corr objects

---

pyerrors/fits.py
tests/fits_test.py

This fixes two bugs that were present in `least_squares` when doing a combined fit with multiple independent variables. The reason for the bug was that transposing the concatenation of the x values did not result in the expected shape. 
This fixes:
- The computation of the number of degrees of freedom works now correctly.
- The computation of the expected chi^2 does not throw an error anymore.
I furthermore discovered that the expected chi^2 with priors is not correctly evaluated. Therefore I have written the tests such that they don't detect this. I think I know what to do, but let's fix this bug first.

Fixed bugs for combined fits with multiple independent variables

---

pyerrors/obs.py
tests/obs_test.py

We now check that each `idx` is sorted in ascending order when creating an `Obs` and provide more helpful error messages when this is not the case.
Closes #214

fix: Check if configs appears multiple times when creating an obs

---

pyerrors/__init__.py
pyerrors/misc.py
pyerrors/special.py
tests/special_test.py

Here is a first draft for a `special` module which adds support for automatic differentation for the Bessel functions implemented in scipy. There are a few more functions which are already supported in `autograd` but I did not explicilty import them yet.
This module could also host functions which are not implemented in scipy, like for example the Lüscher Zeta functions.

Special function module

---

pyerrors/input/openQCD.py

As addressed in #222, this PR introduces an error in case none of the desired idls can be found in the file of the respective replica.

Throw error when trying to only find idls that are not present

---

.github/workflows/pytest.yml

Yesterday's pandas 2.2.0 release includes the following warning:
```
DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
```
which causes our pipeline to fail because of the strict `-Werror` setting.
This PR adds `pip install pyarrow` to the workflow which should silence the warning and fix our piepline.

[ci] Install pyarrow in pytest workflow to silence pandas warnings.

---

pyerrors/input/sfcf.py
tests/sfcf_in_test.py

Hi,
this is the first version of an implementation to solve #225. This is using a list of lists.
It can easily be adapted to use dicts.

Fix keyword files with list of lists

---

pyerrors/obs.py
tests/obs_test.py

Hi,
there is a bug in the error computation when one encounters the case where one combines two Obs from the same ensemble and fluctuations on one (or several) replica are not part of one of the Obses. A scaling factor needs to be applied to the fluctuation. This has been taken care of in the case of missing measurements inside a replica, but not yet on the level of the replica themselves.
I have written a first version of a fix for the case of simple Obs. If we agree that this is a good implementation or find a better one (I was not really sure when it is best to apply the scaling), this has to be extended to the arraymode.
The test routine contains the case that is erroneous in the current version and includes an analytic check of a simple case as well as some more complicated ones.

[fix] Handle missing replia

---

pyerrors/input/sfcf.py

Hey, I just noticed a small bug fir `read_sfcf_multi`, that turns up, when trying to read boundary-to-boundary correlators and boundary-bulk correlators in one go.
Looking up the time extend `T` of the respective correlator helps :)

bugfix: read bb and bib/bi corr in one with keyed_out

---

pyerrors/fits.py
tests/fits_test.py
tests/linalg_test.py
tests/obs_test.py

It was not possible to perform combined fits which rely on more than one x-obs when the data sets had unequal numbers of observations. The case that failed is given in the newly implemented test function. 
The bugfix ensures that the data sets are combined appropriately.

fix: corrected bug that prevented combined fits with multiple x-obs in some cases

---

.github/workflows/release.yml

This PR introduces a release workflow that automatically releases a new version on PyPI whenever a release is created on GitHub. This should simplify releases and allow everyone with collaborator permissions on GitHub to release a new PyPI version @s-kuberski @jkuhl-uni. I can also grant these permissions to @JanNeuendorf and @PiaLJP if you are interested.
Here is a summary of our current release process:
1. Update CHANGELOG and README. Bump version number in `pyerrors/version.py` (respecting [semantic versioning](https://semver.org/)).
2. Merge the `develop` branch into `master` (and push to GitHub).
3. Create a GitHub release with target `master`, tag `v2.x.y` and write brief release notes. This will trigger a PyPI release which then triggers a conda-forge release.
4. Bump version …

[Build] Release workflow added.

---

pyerrors/obs.py
tests/obs_test.py

I explicitly added the derivatives for `__pow__` and `__rpow__`, previously these were estimated via autograd. On my machine this results in a ~4x speedup for pow operations, `obs ** 2` is now slightly faster than `obs * obs`.
I removed the `Obs` case from `__rpow__` as this should be covered by `__pow__` already and none of our tests fail 🤞

[Feat] Provide derivatives for pow

---

pyerrors/fits.py
tests/fits_test.py

This pr introduces two basic checks of the properties of the matrix `inv_chol_cov_matrix[0]` that can be passed by the user when a correlated fit is performed. While we cannot ensure that the matrix is correctly constructed, the check if the matrix is lower triangular should filter out all the cases wher the covariance matrix, the correlation matrix or an inverse of either is passed.
I've added the check for positive entries of the diagonal because this is another feature of the matrix. I don't expect the user to provide a matrix with negative diagonal entries that is lower triangular, but it is another easy check for correctness.

[Feat] Introduce checks of the provided inverse matrix for correlated fits

---

pyerrors/input/dobs.py
pyerrors/input/json.py
pyerrors/obs.py
tests/json_io_test.py
tests/linalg_test.py
tests/obs_test.py

This pull request addresses #256:
It removes the possibility to create an `Obs` from data that is based on several ensembles. Whereas the feature is needed internally, it can be considered dangerous for users as the behavior of the function might be unexpected. To allow for internal creation of such `Obs` in intermediate steps, the creation is still allowed if `means` are passed to the function.
Further changes that I introduced along the way because they are coupled to the same problem. It is possible that I have overlooked something. In this case, these changes can be discussed and reverted.
- It is not possible anymore to reweight an `Obs` that already contains several ensembles. The only setting where I see that this could be a valid procedure is the case where algorithmic parameters …

[Fix] Removed the possibility to create an Obs from data on several replica

---

examples/06_gevp.ipynb

I think the description does not match the cell above.

Fixed index in GEVP example
